coverage:
  precision: 2
  round: down
  range: "70...100"
  ignore:
    - Lock/LockOnePasswordExtension.*
    - LockTests/*
    - App/*
  status:
    patch:
      default:
        if_no_uploads: error
    changes: true
    project:
      default:
        target: auto
        if_no_uploads: error
comment: false
